# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false

after_success:
  # Documenter auto-deploy
  # following `using` instruction is for triggering precompilation
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Ju", "docs")); include("make.jl")'
